//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ads.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ad
    {
        public int Id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string price { get; set; }
        public string image { get; set; }
        public string contactName { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string number { get; set; }
        public string location { get; set; }
    }
}
